### ISSUE TITLE
Remove abstract classes as they dont provide any value

### ISSUE THREAD

**Issue by nnatter** [sulu/SuluContentBundle#104]
The implementation of the `AbstractContentRichEntity` class is:
```php
abstract class AbstractContentRichEntity implements ContentRichEntityInterface
{
    use ContentRichEntityTrait;
}
```

The implementations of the `AbstractDimensionContent` and `AbstractContentProjection` look very similar. I think these classes make things harder to understand/confusing while not providing any value.

If the user implements his own custom entity, he will ask himself if he needs to extend the `AbstractContentRichEntity` class or if it is enough to extend the `ContentRichEntityInterface`. Furthermore, the class contains very few code and it is not a problem to just use the `ContentRichEntityTrait` in the custom entity.

Therefore, I think we should remove the following classes from the bundle:
* `AbstractContentProjection`
* `AbstractContentRichEntity`
* `AbstractDimensionContent`

**Comment by alexander-schranz** [comment]
fixed in #105
