### ISSUE TITLE
nosql support

### ISSUE THREAD

**Issue by trickreich** [sulu/SuluContentBundle#185]
In my opinion Sulu nosql support would be awesome.
Not sure if this is working actually?

**Comment by alexander-schranz** [comment]
Not sure about if you talk about storing whole sulu (users, contacts, roles, ...) in a nosql database or just the Content to be stored in NoSQL. Which NoSQL Database you have in your mind? Currently both (core entities) is build on doctrine/orm and need relations to specific entities so currently its not working with a NoSQL Layer.

**Comment by trickreich** [comment]
Get rid of the whole dependency would be great.
Such things are decreasing the complexity!

**Comment by alexander-schranz** [comment]
@trickreich so you talking more about [sulu/sulu](https://github.com/sulu/sulu) making the Admin UI as an own package without any connection to a backend (PHP and Database)? I think currently this is not easy todo as it is connected to symfony and its controllers.

**Comment by alexander-schranz** [comment]
I will close this issue as I think we will not in the near future go away from relational databases like MySQL and PostgreSQL to store our content. Specially as the JSON support in relational databases are getting a lot better.
