### ISSUE TITLE
Routes not deleted after entity was removed from Sulu Admin

### ISSUE THREAD

**Issue by martinlagler** [sulu/SuluContentBundle#197]
The routes of the entities are still in the `ro_routes` table after they were deleted via the Sulu Admin.

**Comment by niklasnatter** [comment]
Thanks for reporting! This is a problem for the built in `Example` entity too.

I can think about two possible solutions:

- Remove the routes in the `deleteAction` of the controller. We already remove the entity from the index explicitly here. The difference is that the entity is indexed explicitly in the controller too, while the routes are created automatically by the bundle.
https://github.com/sulu/SuluContentBundle/blob/bd6674a20de5737a35a3fdfab373a1e495cf75ac/Tests/Application/ExampleTestBundle/Controller/ExampleController.php#L279-L280

- Register a doctrine event listener to remove the routes if a `RoutableInterface` is removed. We could listen to the `postRemove` event for this. We already use a doctrine event listener for adding fields to the orm mapping of the entity:
https://github.com/sulu/SuluContentBundle/blob/bd6674a20de5737a35a3fdfab373a1e495cf75ac/Content/Infrastructure/Doctrine/MetadataLoader.php#L62-L65

**Comment by alexander-schranz** [comment]
@wachterjohannes is this fixed in #198?

**Comment by wachterjohannes** [comment]
@alexander-schranz yes that was the issue - will close it
