### ISSUE TITLE
Use JSONB instead of JSON to store data

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluContentBundle#219]
https://scalegrid.io/blog/using-jsonb-in-postgresql-how-to-effectively-store-index-json-data-in-postgresql/

In doctrine by adding `options: ['jsonb' => true]` will use when available the JSONB fieldtype instead of JSON in database like postgresql which is in most cases the better match as it allow store the data in a binary way and allow so more performant queries.

Should be updated in [MetadataLoader](https://github.com/sulu/SuluContentBundle/blob/0.6.2/Content/Infrastructure/Doctrine/MetadataLoader.php)  `json` types.

**Comment by mario-fehr** [comment]
@alexander-schranz forgot to auto-close this issue.
