### ISSUE TITLE
DimensionRepository should not need a flush

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluContentBundle#35]
Currently the DimensionRepository does need a flush before the Dimension can be loaded this should not be the case, the queries should also keep the new unitofwork entities into it.

When Implemented the Skips can be removed from the tests:

https://github.com/sulu/SuluContentBundle/blob/3ef2765ac1f03f1affbe4fada598c52ab653c677/TestCases/Dimension/DimensionRepositoryTestCaseTrait.php#L63-L65

**Possible Solution**:

Create a collection of unit of work entities and use criteria to filter it.

**Comment by niklasnatter** [comment]
This is not longer relevant because the `DimensionRepository`was removed in https://github.com/sulu/SuluContentBundle/pull/174

**Comment by alexander-schranz** [comment]
@nnatter I think we still have a similar problem with the new DimensionContent when I save a content in a process with `en` and `de` it will create 2. It will create 2 unlocalizedDimension which will then end in a unique constraint error when flusing them.

**Comment by niklasnatter** [comment]
You are right 😕  I saw that you already added #179 for that, so we can keep this closed
