### ISSUE TITLE
Limit attributes of Dimension entity to stage and locale

### ISSUE THREAD

**Issue by nnatter** [sulu/SuluContentBundle#87]
Right now, every `DimensionContent` is associated to exactly one `Dimension`. The idea behind this architecture is to make the `Dimension` class overwritable/extendable. This way, if somebody adds a `targetGroup` attribute to the `Dimension` class, it is available for every `ContentRichEntity` without any additional configuration.

Unfortunately, adding additional properties to the `Dimension` class has complex implications that we have not anticipated. The services for modifying the content need to be aware of the attributes of the dimension to process them correctly. For example, when publishing content, we want to publish the `DimensionContent` for a specific locale but all target groups. This means that adding an additional `targetGroup` requires to change the logic inside the `PublishTransitionSubscriber`

Furthermore, the possibility of adding additional attributes to the `Dimension` class makes a lot of the code of the bundle very abstract/vague/generic and therefore harder to understand. If we would decide to allow only a `stage` and a `locale` attribute, we could simplify a lot of the code and also our interfaces.

**Comment by wachterjohannes** [comment]
Related to #84

**Comment by niklasnatter** [comment]
Closing this as the `Dimension` entity was removed in https://github.com/sulu/SuluContentBundle/pull/174

Furthermore, as explained in https://github.com/sulu/SuluContentBundle/issues/84#issuecomment-759571798, I do not think that we should limit the `dimensionAttributes` anymore.
