### ISSUE TITLE
Provide an abstraction for loading effective DimensionContents for a specific entitiy

### ISSUE THREAD

**Issue by nnatter** [sulu/SuluContentBundle#91]
Within the bundle, it is a recurring task to load the effective `ContentDimension` entites for a given `contentRichtEntitiy` and given `dimensionAttributes`. The `ContentResolver`,  `ContentWorkflow` and `UnpublishTransitionSubscriber` use the following code to achieve this:

```php
$dimensionCollection = $this->dimensionRepository->findByAttributes($dimensionAttributes);

if (0 === \count($dimensionCollection)) {
    throw new ContentNotFoundException($contentRichEntity, $dimensionAttributes);
}

$dimensionContentCollection = $this->dimensionContentRepository->load($contentRichEntity, $dimensionCollection);
```

It might be useful to make this task simpler by providing an abstraction. For example, the `dimensionContentRepository` could provide a `loadByAttributes($contentRichEntity, $dimensionAttributes)` method. This would also make the strategy for loading the effective `ContentDimension` entities consistent throughout the bundle

**Comment by alexander-schranz** [comment]
@nnatter think this is also related to #82/#148. If we make the content resolver able to return the dimensionContentCollection instead which contains also the mergers so the Collection is always able to return the merged view it would be easier for the developer to access a specific dimension or to access the generated merged view.

**Comment by niklasnatter** [comment]
After removing the `DimensionEntity` in https://github.com/sulu/SuluContentBundle/pull/174, the code for loading the effective `ContentDimension`s now looks like this:
```
$dimensionContentCollection = $this->dimensionContentRepository->load($contentRichEntity, $dimensionAttributes);
```
